### ISSUE TITLE
It's possible for run slimta with multi threading ?

### ISSUE THREAD

**Issue by bawonsak** [slimta/python-slimta#100]
It's possible for run slimta with multi threading ? . For increase speed send email.

**Comment by icgood** [comment]
No, it is not possible directly. Slimta uses [gevent](http://www.gevent.org/) which is limited to a single thread. Email servers are generally [I/O bound](https://en.wikipedia.org/wiki/I/O_bound), and will not get the full benefit of additional CPUs.

However, for the savvy, you _can_ use multiple instances of slimta running on different ports to utilize all CPUs, and then use a proxy application such as [haproxy](http://www.haproxy.org/) to load balance to each port. Additionally, you could use the [`send-proxy`](https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#5.2-send-proxy) parameter and configure slimta's [Proxy Protocol support](https://docs.slimta.org/en/latest/manual/edge.html#proxy-protocol-with-smtp-edge) to ensure you see the correct source IP address. I believe this strategy has worked for others.

**Comment by bawonsak** [comment]
If run slimta with same port or without port what will happen.

**Comment by socketubs** [comment]
@bawonsak You can't run slimta (edge) without a port and won't be able to start multiple slimta instance on same port.

This is why @icgood tell you to look at [haproxy](http://www.haproxy.org/).
