### ISSUE TITLE
How to use slimta as simple relay to gmail smtp

### ISSUE THREAD

**Issue by adamszeptycki** [slimta/python-slimta#121]
Hey, 
I would like to use slimta as smiple relay to gmail smpt,
how should I approach that problem?
I know about xoauth2 autorization -> I have token and everyting.
The question is how to setup slimta to just push everything to gmail smtp

**Comment by icgood** [comment]
If you have encountered a bug or have a specific feature request, please open a new issue. This question is too generic to be answered effectively.

[1]: https://github.com/slimta/python-slimta
