### ISSUE TITLE
CeleryQueue and Celery 4

### ISSUE THREAD

**Issue by dimanjy** [slimta/python-slimta#129]
I'm trying to make Slimta work with CeleryQueue, but it looks like it does'nt work anymore with Celery 4 :(

In celeryqueue/\_\_init.py\_\_ line 146:

> TypeError: attempt_delivery() takes exactly 3 arguments (2 given)

It there some workaround for this issue?
As far as I understood, class methods can't be a Celery tasks anymore...

**Comment by thestick613** [comment]
You can use any kind of queue backend you want. Just inherit `SmtpEdge` and override the `handoff` method.

**Comment by dimanjy** [comment]
But I need exactly `CeleryQueue` and it doesn't work :( Now I'm looking for solution, how to make class method work as Celery task properly.

**Comment by thestick613** [comment]
Initialize a Celery queue object in the `SmtpEdge`'s `__init__` and in the `handoff` method call the function that saves your message in that Celery queue.

**Comment by dimanjy** [comment]
@thestick613, thanks for trying to help, but do we talking about the same thingth?

I'm talking about [slimta.celeryqueue](https://docs.slimta.org/en/latest/api/extra.celeryqueue.html) package where `CeleryQueue` is imported from.
This class does exactly what you are suggest to do. And I'm not as much expirienced to make my own class with that kind of functionality :(

All I know is that there is an issue in Celery with class method-based tasks [here](https://github.com/celery/django-celery/issues/258). And I'm not the only one interested in it.

**Comment by icgood** [comment]
Hi @dimanjy, I originally thought Celery would be a good fit for the message [queue][1], but it just wasn't something I could adapt into my design.


[1]: https://www.slimta.org/manual/queue.html
