### ISSUE TITLE
Does slimta do any dot stuffing?

### ISSUE THREAD

**Issue by thestick613** [slimta/python-slimta#130]
https://stackoverflow.com/questions/15224224/smtp-dot-stuffing-when-and-where-to-do-it

**Comment by icgood** [comment]
Yes, it handles dot-stuffing for both inbound and outbound SMTP:
https://github.com/slimta/python-slimta/blob/master/slimta/smtp/datasender.py#L52
https://github.com/slimta/python-slimta/blob/master/slimta/smtp/datareader.py#L84
