### ISSUE TITLE
Connection Control.

### ISSUE THREAD

**Issue by felipeSynus** [slimta/python-slimta#133]
Hi ! Thanks for the Slimta Project.

I'm using Slimta as MTA in my project and i need control connections.

I need of Slimta reject connections of specifics IPs listed in a file.
Someone did it or know how i can do ?

**Comment by icgood** [comment]
Hi @felipeSynus, I believe you could adapt [`slimta.util.dnsbl`](https://www.slimta.org/api/slimta.util.dnsbl.html) to your needs. It is designed to reject connections from DNS blocklists, but I'm sure you could adapt it to reading from a file.
