### ISSUE TITLE
User manual is not available

### ISSUE THREAD

**Issue by vijayabaskarFD** [slimta/python-slimta#149]
The url http://slimta.org/latest/manual/slimta.html is not working.  IT shows usage manual not exists

**Comment by gpatel-fr** [comment]
you can find the user manual here
https://slimta.org/en/latest/#python-library
use the 'next' button for the rest or jump directly to the api reference
https://slimta.org/en/latest/api/index.html
HTH

**Comment by icgood** [comment]
Yes, @vijayabaskarFD as @gpatel-fr mentioned the best way to navigate when a URL changes is to go back to the top level (https://slimta.org/) and navigate where you need to go again. In this case, the URL you are looking for is:

https://slimta.org/en/latest/manual/slimta.html
