### ISSUE TITLE
Fix travis build

### ISSUE THREAD

**Issue by gpatel-fr** [slimta/python-slimta#151]
following https://travis-ci.org/slimta/python-slimta/builds/540897810
Python 3.4 and 3.5 failures are caused by https://github.com/saghul/pycares/issues/90
can be fixed by adding <3 specifier for pycares

Python 3.6 failure seems related to 
https://github.com/gevent/gevent/issues/1424
so probably adding
install:
- pip install --upgrade pip
to travis.yml

Python 3.7 could be added with 
https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905

About the Python 2.7 failure I'm at a loss, but doing the changes for Python 3.6 and 3.7 could possibly fix it since the project tests fine locally with recent library versions.

**Comment by icgood** [comment]
Thanks @gpatel-fr, will take a look ASAP.
