### ISSUE TITLE
DBPageNotFoundError: (-30985, 'DB_PAGE_NOTFOUND: Requested page not found')

### ISSUE THREAD

**Issue by rafaelnovello** [slimta/python-slimta#24]
Hi,

I'm using python-slimta with memory queue and these error has happened some times. Can anyone help?

```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/mailerweb/production/web_app/mailerweb.sender/src/slimta/slimta/queue/__init__.py", line 424, in _dequeue
    envelope, attempts = self.store.get(id)
  File "/home/mailerweb/production/web_app/mailerweb.sender/src/slimta/slimta/queue/dict.py", line 94, in get
    return self.env_db[id], meta['attempts']
  File "/usr/lib/python2.7/shelve.py", line 121, in __getitem__
    f = StringIO(self.dict[key])
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
DBPageNotFoundError: (-30985, 'DB_PAGE_NOTFOUND: Requested page not found')
<Greenlet at 0x253acd0: <bound method Queue._dequeue of <Queue at 0x253aeb0>>('0f52444a795b4a8d892e9a7e7eed6d20')> failed with DBPageNotFoundError
```

**Comment by icgood** [comment]
Hey, I'm not terribly familiar with the inner works of shelve, but my guess is that its [concurrency restrictions](https://docs.python.org/2/library/shelve.html#restrictions) might be at play here. I used shelve as examples because it's extremely easy to use, but it should probably not have any real weight put on it.

If you can, I would recommend using [redisstorage](https://github.com/slimta/python-slimta-redisstorage) (documented [here](http://slimta.org/latest/manual/extensions.html#redis-storage)) as your queue storage engine.

**Comment by rafaelnovello** [comment]
Hi Ian,

I changed the internal queue back to memory and it "solved" the problem.

Now, I would like to ask you if it is possible to share the same redisstorage between many servers running slimta. I'm asking this because I would like to distribute the delivery attempts between different servers.

Thanks for help!

**Comment by icgood** [comment]
Hey @rafaelnovello, sorry for the delay and not sure if you're still working on this. But yes, [redisstorage](https://github.com/slimta/python-slimta-redisstorage) is designed to be distributed, such that an arbitrary number of [Edge](http://slimta.org/latest/api/slimta.edge.html#slimta.edge.Edge) objects can delivery messages to a redis instance, and an arbitrary number of [Relay](http://slimta.org/latest/api/slimta.relay.html#slimta.relay.Relay) objects can attempt delivery off that same redis instance.

I'm going to close this issue for now. Please feel free to re-open as necessary.
