### ISSUE TITLE
Python3 support, why not ?

### ISSUE THREAD

**Issue by JocelynDelalande** [slimta/python-slimta#26]
Hi, simple question to wonder about why Python3 is not supported, 

- is there any blocking reason (like a dependency not being available for python3) ?
- is it just the fact that it's using some python2-specific idioms ? (which can be fixed in reasonable time, the project being well covered with tests)

Thanks by advance.

**Comment by icgood** [comment]
There is a strong, fundamental usage of the [gevent](http://www.gevent.org/) library. Until [version 1.1](http://www.gevent.org/whatsnew_1_1.html), gevent had no support for Python3. I started investigating a switch to eventlet, which had py3 support and seemingly broader usage due to OpenStack, but it was not a drop-in replacement as I had hoped.

I am welll-versed in the idioms that are compatible with py2 and py3, so I will hopefully begin a transition to support both within a few weeks. PRs are also welcome, if you're interested :)

**Comment by JocelynDelalande** [comment]
@icgood thanks for quick reply.



> I am welll-versed in the idioms that are compatible with py2 and py3, so I will hopefully begin a transition to support both within a few weeks. 

Good to hear, that was my conclusion reading your code anyway, appart from string-related things and some imports, it's mostly already py3-compatible (realy nice code btw, congrats !)

> PRs are also welcome, if you're interested :)

Yep, maybe :) I'm currently only evaluating the opportunity to use slimta with a py3-only project at @oasiswork

**Comment by JocelynDelalande** [comment]
For the record, dnspython is currently shipping two versions:

- dnspython for Python 2.x
- dnspython3 for Python 3.x

This is [quite by design](https://github.com/rthalley/dnspython/issues/60#issuecomment-36515271) (or by constraint).

I'm wondering how could we deal with that supporting both python2 and python3 in slimta.

**Comment by icgood** [comment]
Regarding the dnspython and dnspython3, we will probably want to change the setup script to use [environment markers](https://www.python.org/dev/peps/pep-0426/#environment-markers) to specify the different packages based on the python version. These markers are available in newer setuptools.

**Comment by icgood** [comment]
By the way, we're [all green](http://ci.slimta.org/) after merging the switch to `mox3`. Thanks again!

**Comment by JocelynDelalande** [comment]
> Regarding the dnspython and dnspython3, we will probably want to change the setup script to use environment markers to specify the different packages based on the python version. These markers are available in newer setuptools.

That's a really decent workaround :) I didn't know environment markers, thanks :)

Do you know if python 2.7.6 has a recent enough setuptools for that ? (it's the one shipped in ubuntu 14.04, I think that's an important target platform).

PS: is that just me or is it another good reason to drop python 2.6 ? ;-)

**Comment by JocelynDelalande** [comment]
# Unicode/bytes

Getting compatible with python3 require to answer a clear way to the question "what is bytes and what is unicode strings". My proposal on that would be:

- everything internal is unicode (including the data `Envelope` handles)
- we **read** bytes data only at the edges:
  - wsgi `environ` dict
  - socket read from SMTP edge
- we **write** bytes data on the output edge: to the socket with remote destination MTA
- message queues are internal, let's use unicode there (I think *dict*, *relay* and *celery* are playing nice with that)

That approach (encoding/decoding only at the edge) [is quite standard](https://docs.python.org/3/howto/unicode.html#tips-for-writing-unicode-aware-programs).

To offer consistency across python versions with this behavior, I would suggest using `from __future__ import unicode_literals` as much as possible.

@icgood what do you think ?

**Comment by JocelynDelalande** [comment]
# Documentation

Another question is argument type documentation in docstrings.

Currently, there is a lot of places like that:
```
def foo(bar):
    """
    :type bar: :py:obj:`str`
    """
```

Which is fine for Python2, but with python3 we have te distinguish clearly what is unicode (`str` type in python3, `unicode` in py2) and what is bytes (`str` or `bytes` in py2>=2.6 and `bytes` in py3). 

*nb: `unicode` is no longer a valid keyword/type in py3.*

So, there is no ideal solution as far is I know

**Comment by icgood** [comment]
Agreed on the python3 model. :+1:

**Comment by JocelynDelalande** [comment]
> Agreed on the python3 model. :+1:

Except maybe on the fact that raw message body should be kept as bytes in the `Enveloppe` object, as we discussed by email.

**Comment by JocelynDelalande** [comment]
> Do you know if python 2.7.6 has a recent enough setuptools for that ? (it's the one shipped in ubuntu 14.04, I think that's an important target platform).

So, it's setuptools related, and got included [starting with setuptools 0.7](https://pypi.python.org/pypi/setuptools/1.1.6#id33), so it's fine, but I can't find since when it's included in distutils.

**Comment by icgood** [comment]
Python 3 support will be available in `python-slimta` versions >= 3.0.0 thanks to the extensive work of @JocelynDelalande! Thank you!
