### ISSUE TITLE
RelayPolicy example + doc

### ISSUE THREAD

**Issue by JocelynDelalande** [slimta/python-slimta#27]
core code comes with [3 `QueuePolicy` examples](http://slimta.org/latest/api/slimta.policy.html), but no `RelayPolicy` example. Moreover, what the `RelayPolicy` should return is not documented.

**Comment by JocelynDelalande** [comment]
Don't know if that is intended, but it seems to me that `RelayPolicy` can raise `TransientRelayError` or `PermanentRelayError` themselves. is that on purpose ? If yes, it should be documented.

**Comment by icgood** [comment]
I have not added a `RelayPolicy` example to the docs yet, but I did fill in the [`RelayPolicy.apply`](http://slimta.org/latest/api/slimta.policy.html#slimta.policy.RelayPolicy.apply) method documentation as you suggested :)

**Comment by JocelynDelalande** [comment]
@icgood cool, thank you :+1:
