### ISSUE TITLE
any way of convincing StaticSmtpRelay to use a certain ip when relaying an email?

### ISSUE THREAD

**Issue by thestick613** [slimta/python-slimta#28]
I am using slimta for a custom whitelabel transactional email platform. I am using slimta for antispam, authentication and some other taks, but i forward all the emails to a sendgrid account. I'd like to change that in the future, and deliver the emails myself. I want to create 2-3 ip pools for each customer rating (good, bad, neutral) so i can segregate my traffic on different ips, eventually based on target domain as well.
I was thinking starting one or more instances based on StaticSmtpRelay per each ip, and read the incoming mails from a distributed message queue. Is there a better solution which i'm missing?
Thanks.
btw great library.

**Comment by icgood** [comment]
It is possible, yes. There is an undocumented argument to both `StaticSmtpRelay` and `MxSmtpRelay` that lets you control how the socket is created:

```python
import random
source_ips = ['1.2.3.4', '1.3.5.7', '2.4.6.8']

def _socket_creator(address):
    bind_ip = random.choice(source_ips)
    return create_connection(address, source_address=(bind_ip, 0))

mx = MxSmtpRelay(socket_creator=_socket_creator)
```

Basically, it sounds like you'll want to implement a custom Relay that keeps a pool of `MxSmtpRelay` objects, one bound to each IP. When `attempt` is called on your Relay, you can inspect the envelope to determine which `MxSmtpRelay` and thus which bound IP to use for delivery.

**Comment by thestick613** [comment]
Great, i guess you may close the issue!
