### ISSUE TITLE
Run CI on pull requests

### ISSUE THREAD

**Issue by JocelynDelalande** [slimta/python-slimta#32]
I don't know how the CI works, but it seems to me a bit risky to run it only on master and not on pull requests, 

@icgood would it be hard to set up ?

**Comment by icgood** [comment]
Done. This was something I'd been meaning to do for a while!

**Comment by JocelynDelalande** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Ian Good <notifications@github.com> wrote:
> Done. This was something I'd been meaning to do for a while!

Cool, thanks :)

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.12 (GNU/Linux)

iQIcBAEBAgAGBQJWNxV2AAoJEOodh6AvlLNT9NkP/0+U+NDnlXp37kUngbmh8OJk
w6NAk0GlufEbH3yHAm9ifUHYATFYfz4AycoGC+LFmFnyLuvS3lZ2jCmkhp7PrHuL
MY6pPyxEUl+qtMv7AEJU+Db9f60HaiRiUxMo2EkO3yMz+k8jFAJnp72FZMYx1ayn
CifV1LOqakdrBSWedGGh9ZjNOuVIegOuKxfoLgXIAwu3vRFx8LG1KbRaJm2SGjbX
WilqQZoEzdwIJfDPCRA62nnZwFcMmC0kqOTlJ082kOR9ebO/JbYtAjtBXiuA0T3/
9HnK1EBjuzAnzv/C6MneRNyuUj+ClTPkanXJP5AM9quAUWKtDKmFm1jDLYcWV0Uk
KHaSnzC58WD/CKd8gyce7Dl1FWLTiye++VtPn+GQySiQj6wiIag/Bm3yCY0BxiW+
6G0wADECltVvFjtv7eMs3s6shBXtL2nczfqoaRtPmIOCF232WxNvv0b1jwqQv5Xx
5dVbkHf5A0lNussc8tgR6CCqC63yV8+lzLWU2gGWpENlVa764qqQ3pZMRU3nm07+
qENfwCV5flzR+qquiXKA2W7S02WVSyOweQ1gn3t7ImtS1fzcHW8c55RkXB+yf8oT
oqc6+mbaV8PQAgGpKr3iB4Y/z2vnIL3xnOu1ilGzG/yf5hE1sPii2TekUEsyZu29
I0JCl3R9ca2LeXROjA/g
=v8Su
-----END PGP SIGNATURE-----
