### ISSUE TITLE
examples/slimta-mail.py is broken

### ISSUE THREAD

**Issue by JocelynDelalande** [slimta/python-slimta#37]
Auth has changed at 7db29cef093ac5a219c1b3c25f1380be3515ccff but it seems that *examples/slimta-mail.py* got forgotten in the process :)

I tried to fix it quickly but it's not that simple, as there is no simple example to look at (cause this *is* the simple example :p). 

@icgood mind to give a look at fixing it if you get some time ?

**Comment by icgood** [comment]
Fixed in a3744bc7c4837f2c49b24dd9b29cde5cab882db5.
