### ISSUE TITLE
haproxy support for original ip address

### ISSUE THREAD

**Issue by thestick613** [slimta/python-slimta#45]
Slimta works great with haproxy, but when you need to saturate all CPU cores, you end up starting more inbound processes. Haproxy helps with that, but it also hides the original ip address. There seems to be a PROXY protocol that both postfix and haproxy support, but i haven't made much of it, even after trying it up with wireshark:

http://permalink.gmane.org/gmane.comp.web.haproxy/8881
http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt

Then i found this:
https://pypi.python.org/pypi/pwho/0.1.0

Before i start messing up with this, is there another way of obtaining the original ip address of the sender? I might have overlooked.
Thanks.

**Comment by icgood** [comment]
I actually really liked this idea, I have had this same problem many times in the past. I whipped up a quick implementation of proxy protocol v1 in #46. If you don't want to pull `master`, you're welcome to [download the module](https://raw.githubusercontent.com/slimta/python-slimta/master/slimta/util/proxyproto.py) directly, as it should be compatible with previous versions. Usage is basically like this:

```python
from slimta.edge.smtp import SmtpEdge
from slimta.util.proxyproto import ProxyProtocolV1

class MyEdge(ProxyProtocolV1, SmtpEdge):
    pass

# Then you just change however you instantiated SmtpEdge to instantiate MyEdge instead...
edge = MyEdge(('', 25), queue)
edge.start()
```

**Comment by icgood** [comment]
> Before i start messing up with this, is there another way of obtaining the original ip address of the sender? I might have overlooked.

Unfortunately not that I can think of. The only other option was Postfix's `XCLIENT` extension, which is very complicated and I was hesitant to try and implement it.

**Comment by thestick613** [comment]
Very nice work. Thanks!

**Comment by NicolasLM** [comment]
Hi, I need to implement `XCLIENT` for my own need - it is the only option compatible with nginx. It does not look that complicated.

Do you want me to implement it in slimta?
