### ISSUE TITLE
StaticSmtpRelay does not seem to care about connect_timeout or command_timeout

### ISSUE THREAD

**Issue by thestick613** [slimta/python-slimta#49]
I've sent an email to a colleague's email server using a StaticSmtpRelay, and i've receive this traceback

    Traceback (most recent call last):
      File "debug_slowconn/1.py", line 20, in <module>
        mx.attempt(new_envelope, 0)
      File "/root/venv_smtpout/site-packages/slimta/relay/smtp/mx.py", line 220, in attempt
        return relayer.attempt(envelope, attempts)
      File "/root/venv_smtpout/site-packages/slimta/relay/pool.py", line 93, in attempt
        return result.get()
      File "/root/venv_smtpout/site-packages/gevent/event.py", line 294, in get
        return self.get(block=False)
      File "/root/venv_smtpout/site-packages/gevent/event.py", line 273, in get
        return self._raise_exception()
      File "/root/venv_smtpout/site-packages/gevent/event.py", line 254, in _raise_exception
        reraise(*self.exc_info)
      File "/root/venv_smtpout/site-packages/gevent/_util_py2.py", line 8, in reraise
        raise type, value, tb
    SmtpTransientRelayError: Transient failure on [unknown command]: 421 4.3.0 Connection was closed prematurely

The culprit seems to be in `slimta/smtp/io.py` in `raw_recv`, in the second `raise ConnectionLost()`. The destination MX is accepting my SMTP connection, but it doesn't greet me until it can resolve my reverse ip, so the connection hangs for 20-21 seconds. After that, i get a nice greeting from exim and i could carry on. Unfortunately, slimta hangs and dies. Have you managed to get this error in production? May this be signaling a bigger bug?

**Comment by icgood** [comment]
I'm executing this script:

```python
from slimta.envelope import Envelope
from slimta.relay.smtp.static import StaticSmtpRelay

env = Envelope('sender@example.com', ['rcpt@example.com'])
relay = StaticSmtpRelay('localhost', 1025)
relay.attempt(env, 0)
```

In another console, I'm running this: `nc -k -l 1025`

If I Ctrl-C the `nc` command before the 10 second `command_timeout`, I get the error you're seeing:

```
slimta.relay.smtp.SmtpTransientRelayError: Transient failure on [unknown command]: 421 4.3.0 Connection was closed prematurely
```

If I don't Ctrl-C the `nc` command and let the 10 seconds elapse, I get this error:

```
slimta.relay.smtp.SmtpTransientRelayError: Transient failure on [unknown command]: 421 4.4.2 Connection timed out
```

It seems to me like this is working as intended. Are you sure this remote server is not closing the connection? What happens when you use something like `nc` or `telnet` to connect to the remote server?

**Comment by thestick613** [comment]
I've tried running a server like this:

    #!/usr/bin/python
    
    from gevent import monkey
    monkey.patch_all()
    
    import gevent
    from slimta.edge.smtp import SmtpEdge, SmtpValidators
    import time
    
    class MyValidator(SmtpValidators):
        def handle_banner(self, reply, address):
            time.sleep(21)
            reply.message = """s2.server.com ESMTP Exim 4.86 #2 Wed, 16 Dec 2015 12:44:06 +0200 
    We do not authorize the use of this system to transport unsolicited, 
    and/or bulk e-mail."""
    
    class MySmtpEdge(SmtpEdge):
        def __init__(self, listener, queue):
            super(MySmtpEdge, self).__init__(listener=listener, queue=queue, hostname="hostname",
                                             validator_class=MyValidator, data_timeout=180.0,
                                             command_timeout=180.0)

        def handoff(self, envelope):
            print envelope
            return [(envelope, "")] 

    edge = MySmtpEdge(listener=('0.0.0.0', 10025), queue=None)
    edge.start()
    gevent.joinall([edge])

But i haven't been able to reproduce it, so i guess the problem is somewhere else.

**Comment by thestick613** [comment]
Well, according to a tcpdump, this whole error happens AFTER the QUIT. How do i enable the slimta SocketLogger?

**Comment by thestick613** [comment]
Well, what actually happened was that exim replyed to me with 
`'550 Access denied - Invalid HELO name (See RFC2821 4.1.1.1)'`
immediately after i sent the DATA part, then closed the socket. It had nothing to do with the initial timeout. Closing this in favor of #50.
