### ISSUE TITLE
Include command in SmtpRelayClient errors

### ISSUE THREAD

**Issue by icgood** [slimta/python-slimta#50]
The error reply generated [here](https://github.com/slimta/python-slimta/blob/master/slimta/relay/smtp/client.py#L236) does not properly carry over the `command` field of the original `Reply` that caused the exception. This causes errors to say `[unknown command]` even when they happened while waiting for the response to a command.

**Comment by thestick613** [comment]
This actually hurts me the most right now. If you want to debug this, try mailing to an exim server with an invalid ehlo, such as 'asdf'. It will allow you do do a part of the smtp transaction, but after you send the DATA you will get an error response and a closed socket.
