### ISSUE TITLE
Patch SmtpSession.HAVE_DATA to respond with the result of the handoff

### ISSUE THREAD

**Issue by thestick613** [slimta/python-slimta#56]
Are you against replacing
`reply.message = '2.6.0 Message accepted for delivery with id'`
with
`reply.message = '2.6.0 Message accepted for delivery with id %s' % results[0][1]`?

My queue mechanism replies with a unique transaction id when i succesfully save to it, and i liked to display that in the smtp session.
Besides checking if results[0][1] is not an error or something like that, it's not used elsewhere.
I'm actually using a patched version of HAVE_DATA in production and it seems like a nice feature. I think i saw a reference to this feature somewhere around here, but i don't find it.

**Comment by icgood** [comment]
Interesting question. I'm looking at the code and you're right, it would be nice to be able to control the reply message there like most of the other commands can do. I might try to re-think where the callbacks happen and allow you to set this message more easily in your own code, but that should do the trick too I think.

**Comment by icgood** [comment]
In the master branch, there is now a `handle_queued` callback that runs after the message(s) are queued, before the reply is returned. It is passed in the `Reply` and the return value of [`enqueue`](https://slimta.org/latest/api/slimta.queue.html#slimta.queue.Queue.enqueue). See [`slimta.edge.smtp`](https://slimta.org/latest/api/slimta.edge.smtp.html) for details.
