### ISSUE TITLE
Evaluate usefulness of Reply.command attribute

### ISSUE THREAD

**Issue by icgood** [slimta/python-slimta#66]

**Comment by icgood** [comment]
If this attribute is not useful, set it to `None` always and remove it next major release.

**Comment by thestick613** [comment]
I am using Reply in a couple of different spots, and access to the raw response is useful.

**Comment by icgood** [comment]
Yeah, I specifically mean the `reply.command` attribute. I had to duplicate some if its functionality in the SMTP relay client, so I'm not sure if it's still useful as-is.

**Comment by thestick613** [comment]
I'll probably have to look in all the changes in 3.0.0, but, whatever you do, don't remove the possibility of:
- implementing a custom smtp scenario and reading smtp responses from the server as they come

**Comment by icgood** [comment]
I consider that a fundamental behavior of the library, it's not going anywhere :smiley:

The attribute I'm referring to was intended to be informational, used for logging and error-handling. I am not sure that it is still valuable in that capacity. The rest of the `Reply` behavior will remain unchanged.

**Comment by icgood** [comment]
Verdict: still useful, leaving as-is.
