### ISSUE TITLE
How to set out bound ip

### ISSUE THREAD

**Issue by bawonsak** [slimta/python-slimta#70]
I have multi ip address for send email. How to swap ip address if blacklist ip.

**Comment by icgood** [comment]
Hey @bawonsak, what you're looking for is the `socket_creator` parameter to the [`MxSmtpRelay`](https://slimta.org/latest/api/slimta.relay.smtp.mx.html#slimta.relay.smtp.mx.MxSmtpRelay) or [`StaticSmtpRelay`](https://slimta.org/latest/api/slimta.relay.smtp.static.html#slimta.relay.smtp.static.StaticSmtpRelay) constructor. This process is quite common and we get this question a lot, so I just now added a new section to the usage manual:

https://slimta.org/latest/manual/relay.html#changing-source-ip

**Comment by bawonsak** [comment]
Do you have some examples.I don't know how to use.
