### ISSUE TITLE
How to save Queue and retry send email again.

### ISSUE THREAD

**Issue by bawonsak** [slimta/python-slimta#71]
HI,I want save queue if in case bounce and retry send email 5 times, If retry send 5 times and bounce remove queue.

**Comment by icgood** [comment]
Hi there, the behavior your looking for is the `bounce` argument to the [`Queue`](https://docs.slimta.org/en/latest/api/slimta.queue.html#slimta.queue.Queue) constructor, and is documented here:

https://docs.slimta.org/en/latest/manual/queue.html#delivery-attempts
