### ISSUE TITLE
raising ConnectionLost with Connection was closed prematurely instead of showing real message

### ISSUE THREAD

**Issue by thestick613** [slimta/python-slimta#73]
If you are mailing an e-mail to yahoo, yahoo may sometimes reply with 
`421 4.7.0 [TS01] Messages from x.x.x.x temporarily deferred due to user complaints - 4.16.55`
during or before greeting, helo/ehlo or at any point, actually. I'd be interested in obtaining that message, because i can take different actions according to the reply. Instead, i just get an
`SmtpTransientRelayError` and a `reply.code='421'`, `reply.message='4.3.0 Connection was closed prematurely'`.

**Comment by thestick613** [comment]
Can we store in the `reply`, besides the `code` and the `message`, the server's last response in a different key?

**Comment by socketubs** [comment]
I think storing host, port, ip of source and destination in `Reply` can be a nice idea too.

**Comment by thestick613** [comment]
Or if the last reply of the server is either a 421 or a 221 (see #57), return THAT message instead of assuming the connection was closed with no reasonable reason.

**Comment by thestick613** [comment]
This is easy to reproduce by creating a SmtpEdge server which replies with 421 on greet or handle_rcpt or handle_mfrom.
