### ISSUE TITLE
Before sending email connect socket creator every round?

### ISSUE THREAD

**Issue by bawonsak** [slimta/python-slimta#86]
#28 
I set loop to send email. I want to know before sending the email  slimta connect socket_creator every round or not.

**Comment by icgood** [comment]
Yes, `socket_creator` will be called for every email you send through the [`StaticSmtpRelay`](https://docs.slimta.org/en/latest/api/slimta.relay.smtp.static.html) or [`MxSmtpRelay`](https://docs.slimta.org/en/latest/api/slimta.relay.smtp.mx.html).

However, if you use the `idle_timeout` option (see docs), then `socket_creator` will only be called for new connections, when there is no available idle connection open.

**Comment by bawonsak** [comment]
How to set one socket_creator of one queue.
