### ISSUE TITLE
Banner validation

### ISSUE THREAD

**Issue by zacbri** [slimta/python-slimta#89]
Hi,

is there an expected format for the welcome banner received from the remote MX ?
I can see the following exchange: 

remote -> me: 220 laposte
me -> remote: QUIT
remote -> me : 221 2.0.0 Bye

and a ConnectionLost exception is raised (I guess, based on the return smtp code/message)

Is that expected behaviour ?

Side note: we have STARTTLS configure on our slimta MX relay, but the remote end doesn't seem to support TLS.
Could this be related ? Does slimta enforce TLS if configured or does opportunistic TLS ?

**Comment by thestick613** [comment]
you need the string 'ESMTP' or 'SMTP' in the greeting.

**Comment by zacbri** [comment]
Thanks @thestick613. Yes, that's what I thought too.
The tests seem to show otherwise though: see [this smtp client test](https://github.com/slimta/python-slimta/blob/master/test/test_slimta_smtp_client.py#L28)

After more troubleshooting it looks like they're using Postscreen with a relatively long delay (15 sec or so) and Slimta's smtp client is talking too soon.

# telnet smtpz4.laposte.net 25
Trying 194.117.213.1...
Connected to smtpz4.laposte.net.
Escape character is '^]'.
220-laposte
220 lpn-prd-vrin019 ESMTP Postfix (Ubuntu)

So just to make things clearer, the SMTP conversation I provided seems to have been mangled bt tshark.
The proper order is probably 220 -> 221 Bye -> QUIT
So Slimta's doing it's job correctly.

Oddly enough, I don't seem to have any problem when sending to our own servers which use Postscreen too but with a 6 seconds delay. But I've setup cache so my connections are quickly getting whitelisted. I'll try and setup another test environment for that.

Back to Slimta, we could probably handle Postscreen-like bots detection since the first banner is formatted differently (220-) and wait for the actual banner.
I have to say this part of the code isn't the easiest to get a grasp on. I'll give it a shot but if you or @icgood have any pointers feel free :)

**Comment by zacbri** [comment]
Ok scratch that.
After re-reading the code I figured slimta was catching the fake banner correctly.
I got timeout errors on subsequent attempts, which led me to the actual issue : connect_timeout on the relay (default to 10) which wasn't enough.
Closing this.
